### ISSUE TITLE
能做一个openwrt的版本吗？

### ISSUE THREAD

**Issue by imoldchen** [UJX6N/bbrplus-5.4#3]
这个patch脚本用在编译openwrt，但是好像并不成功，虽然用 sysctl net.ipv4.tcp_available_congestion_control 
可以查到 bbrplus，但是用 lsmod | grep bbrplus 没有输出任何内容，不知道少了什么。

**Comment by UJX6N** [comment]
> lsmod | grep bbrplus 没有输出任何内容

lsmod | grep bbrplus 没有输出任何内容——是正常的，因为没有做成内核mod，而是编译进内核了，所以lsmod没有

一个模块可以编译为内核mod（mod加载后用lsmod可以查到），也可以编译进内核（lsmod查不到），这补丁是编译进内核

要这样看有没有bbplus：

sysctl net.ipv4.tcp_available_congestion_control

**Comment by imoldchen** [comment]
还有一个问题，在编译 5.4.87 内核的时候有3项选择，最后一项我记得是第一次编译默认是能选 fq 的，但后面再编译就只能选 fq_codel 和 pfifo_fast ，也就是 net.core.default_qdisc 没有了 fq，用了 make clean 还是一样，sysctl 修改为 fq 应用时会提示 sysctl: write error: No such file or directory。
是不是 net/sched/Kconfig 这个文件的修改有问题？
![2021-01-12 035917](https://user-images.githubusercontent.com/14952222/104231922-9364aa00-548a-11eb-8b7a-5e8ad782ac51.jpg)

另外，据说 cake 的表现比 fq 和 fq_codel 更好，能否默认编译 cake 呢，现在默认是没有编译进去。
附上 net/sched/Kconfig 文件
[Kconfig.txt](https://github.com/UJX6N/bbrplus-5.4/files/5798050/Kconfig.txt)
