### ISSUE TITLE
这个是给centos7还是8用的？

### ISSUE THREAD

**Issue by jinwyp** [UJX6N/bbrplus-5.4#4]
建议把各个版本的bbr plus 统一到一个仓库

然后区分是centos7 还是centos8 

就像这种
https://github.com/cx9208/bbrplus

现在都不知道用哪个版本，是针对哪个系统的。

还有希望提供 kernel，kernel-devel，kernel-headers 的编译版本 这样就能装 WireGuard 了

**Comment by UJX6N** [comment]
> 
> 
> 建议把各个版本的bbr plus 统一到一个仓库
> 
> 然后区分是centos7 还是centos8
> 
> 就像这种
> https://github.com/cx9208/bbrplus
> 
> 现在都不知道用哪个版本，是针对哪个系统的。
> 
> 还有希望提供 kernel，kernel-devel，kernel-headers 的编译版本 这样就能装 WireGuard 了

大哥我有些懵逼。release的发布文件名，比方5.4.101，提供给centos的二进制包有

CentOS-7_Required_kernel-bbrplus-5.4.101-1.bbrplus.el7.x86_64.rpm
CentOS-7_Optional_kernel-bbrplus-devel-5.4.101-1.bbrplus.el7.x86_64.rpm
CentOS-7_Optional_kernel-bbrplus-headers-5.4.101-1.bbrplus.el7.x86_64.rpm

CentOS-8_Required_kernel-bbrplus-core-5.4.101-1.bbrplus.el8.x86_64.rpm
CentOS-8_Optional_kernel-bbrplus-5.4.101-1.bbrplus.el8.x86_64.rpm
CentOS-8_Optional_kernel-bbrplus-devel-5.4.101-1.bbrplus.el8.x86_64.rpm
CentOS-8_Optional_kernel-bbrplus-headers-5.4.101-1.bbrplus.el8.x86_64.rpm
CentOS-8_Optional_kernel-bbrplus-modules-5.4.101-1.bbrplus.el8.x86_64.rpm
CentOS-8_Optional_kernel-bbrplus-modules-extra-5.4.101-1.bbrplus.el8.x86_64.rpm

其中
凡是叫CentOS-7什么的当然就是给centos 7的
叫CentOS-8什么的是给centos 8的

当然其实给7用的包，在8上也能用，但好像没必要......

另外含有Required的是必装的，含有Optional的选装的。

我这么命名文件名希望大家能一眼看懂😱
